### ISSUE TITLE
`cannot open </usr/bin/gnuplot -persist > /dev/null 2>&1> in mode w`

### ISSUE THREAD

**Issue by hughperkins** [torch/gnuplot#11]
Hi,

gnuplot is great :-)

After running for a few minutes, or perhaps for a few plots, I get:
```
^C/home/user/torch/install/bin/luajit: cannot open </usr/bin/gnuplot -persist > /dev/null 2>&1> in mode  w at /home/user/git/torch7/lib/TH/THDiskFile.c:585
stack traceback:
	[C]: at 0x7f5fdc71ce10
	[C]: in function 'PipeFile'
	/home/user/torch/install/share/lua/5.1/gnuplot/gnuplot.lua:134: in function 'getfigure'
	/home/user/torch/install/share/lua/5.1/gnuplot/gnuplot.lua:736: in function 'filefigure'
	/home/user/torch/install/share/lua/5.1/gnuplot/gnuplot.lua:754: in function 'pngfigure'
```

Simple script that reproduces the problem:
```
require 'paths'
require 'gnuplot'

local d = torch.Tensor(2000):uniform()

for i=1,2000 do
  gnuplot.pngfigure('/tmp/foo.png')
  gnuplot.plot(d)
  gnuplot.plotflush()
end
```
Since the problem seems to be related more to how often I call the inner loop, rather than elapsed time, I guess there is something I need to clean up after each plot perhaps?

**Comment by koraykv** [comment]
You should have gnuplot.close(ff) where ff is return value from gnuplot.pngfigure. Every call to pngfigure creates a new figure, so you end up having too many gnuplot processes and pipes for each one of them.

**Comment by hughperkins** [comment]
Great!  Thanks! :-)

**Comment by hughperkins** [comment]
Great!  Thanks! :-)
