### ISSUE TITLE
plot 2D/3D points with labels

### ISSUE THREAD

**Issue by octavian-ganea** [torch/gnuplot#35]
Is it possible to plot 2d/3d points with labels? That would be useful for visualizing word embeddings for example. Thanks.

**Comment by Atcold** [comment]
You can use the `gnuplot.raw()` function to enable it.

**Comment by suryabhupa** [comment]
As an example, for anyone wondering in the future:

```
    g.pngfigure('plots.png')
    g.title('Plots of data')
    g.raw("plot 'data.txt' using 2:3:(sprintf('(%d)', $1)) with labels point pt 7 offset char 1,1 notitle")
    g.raw("set term png size 1280, 960") -- sets size of plot
    g.xlabel('x')
    g.ylabel('y')
    g.plotflush()
```

where `data.txt` might look like this:

```
1     0.34    0.5
2     0.26    0.6
3     0.11    0.7
...
```

**Comment by suryabhupa** [comment]
However, are there ever plans to add labeling support natively? Labels seem important and someone not versed in gnuplot may struggle with finding the right raw command.

**Comment by soumith** [comment]
@suryabhupa the answer is no, unless someone sends a PR.

**Comment by suryabhupa** [comment]
While the labeling might be more of a specific case, I can add an example in the docs?

**Comment by soumith** [comment]
sounds good

**Comment by suryabhupa** [comment]
See #39.
