### ISSUE TITLE
How to use gnuplot to plot graph in different terminals?

### ISSUE THREAD

**Issue by oya163** [torch/gnuplot#37]
Suppose I want to plot `torch.logspace(5,10,10)` and `torch.linspace(5,10,10) `in two separate windows, how do I do it? 
I tried using `gnuplot.setterm` but I am not able to figure it out exactly. Any help would be appreciated, thank you.

**Comment by Atcold** [comment]
`gnuplot.figure(n)`, where `n` is an integer.

**Comment by oya163** [comment]
Great. Thank you Alfred.
